### ISSUE TITLE
GET /loginGoogle/callbackGoogle?code=4

### ISSUE THREAD

**Issue by Bashar12345** [shashi278/social-auth-kivy#21]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

 * Serving Flask app 'kivyauth.desktop.utils' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
  * Running on https://127.0.0.1:9004 (Press CTRL+C to quit)
 127.0.0.1 - - [19/Apr/2022 10:24:18] "GET /loginGoogle HTTP/1.1" 302 -
 [2022-04-19 10:24:21,946] ERROR in app: Exception on /loginGoogle/callbackGoogle [GET]
 Traceback (most recent call last):
   File "/home/b/Desktop/RED_Mobile_App/kivy_venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/b/Desktop/RED_Mobile_App/kivy_venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/home/b/Desktop/RED_Mobile_App/kivy_venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
     rv = self.dispatch_request()
   File "/home/b/Desktop/RED_Mobile_App/kivy_venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
   File "/home/b/Desktop/RED_Mobile_App/kivy_venv/lib/python3.8/site-packages/kivyauth/desktop/google_auth.py", line 111, in callbackGoogle
     close_server()
   File "/home/b/Desktop/RED_Mobile_App/kivy_venv/lib/python3.8/site-packages/kivyauth/desktop/utils.py", line 45, in close_server
     raise RuntimeError("Not running with the Werkzeug Server")
 RuntimeError: Not running with the Werkzeug Server
 127.0.0.1 - - [19/Apr/2022 10:24:22] "GET /loginGoogle/callbackGoogle?code=4/0AX4XfWgEP2SEYoY5NqH8S81w-gG7Eq29tG9EbCKCCOX3MIyWRh9Raqkf2fjzQJrYNpZhzA&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&authuser=0&hd=diu.edu.bd&prompt=consent HTTP/1.1" 500 -

**Comment by shashi278** [comment]
Few people's been complaining this issue. I still haven't looked at this yet. I'll look into it as soon as I get some time.

**Comment by juaone1** [comment]
@shashi278  has this issue been fixed?

**Comment by shashi278** [comment]
@juaone1 Not yet. Maybe this weekend.

**Comment by shashi278** [comment]
@Bashar12345 @juaone1 It's been fixed in the latest release 2.3.3. Closing this issue for now but feel free to open up a new one if you still face any issue. Thanks for pointing this out!
